name: Integration Test

on:
  workflow_dispatch:

jobs:
  container-integration:
    name: Victoria container integration
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      IMAGE: ghcr.io/elcanotek/victoria-terminal:latest
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure OPENROUTER_API_KEY secret is available
        if: ${{ env.OPENROUTER_API_KEY == '' }}
        run: |
          echo "::error::OPENROUTER_API_KEY secret is not configured."
          exit 1

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Authenticate to GitHub Container Registry
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GHCR_TOKEN}" | podman login ghcr.io -u "${GHCR_USERNAME}" --password-stdin

      - name: Pull Victoria Terminal container image
        run: podman pull "${IMAGE}"

      - name: Verify crush CLI is installed
        run: |
          podman run --rm --network=none "${IMAGE}" crush --version

      - name: Prepare Victoria home directory
        run: mkdir -p victoria-home

      - name: Run Prime Directive integration check
        run: |
          set +e
          read -r -d '' task_prompt <<'EOF'
          Explain Victoria's Prime Directive and the advertising data sources it can connect to.

          Write the full response to /workspace/Victoria/prime-directive.txt. The file must clearly mention:
          - that Victoria aggregates numerators and denominators before division when computing ratios
          - that Victoria can connect to Snowflake as a data source

          End the response with a short call-to-action inviting the reader to explore Victoria further.
          EOF
          output=$(timeout 90s podman run --rm \
            --userns=keep-id \
            --security-opt=no-new-privileges \
            --cap-drop=all \
            -e OPENROUTER_API_KEY \
            -e VICTORIA_HOME=/workspace/Victoria \
            -v "${PWD}/victoria-home:/workspace/Victoria:Z" \
            "${IMAGE}" \
            -- \
            --accept-license \
            --task "${task_prompt}")
          status=$?
          set -e

          echo "${output}"

          if [ "${status}" -ne 0 ] && [ "${status}" -ne 124 ]; then
            echo "::error::Victoria launch exited with status ${status}" >&2
            exit "${status}"
          fi

          output_file="victoria-home/prime-directive.txt"
          if [ ! -f "${output_file}" ]; then
            echo "::error::Expected response file ${output_file} was not created" >&2
            exit 1
          fi

          echo "--- Victoria task output ---"
          cat "${output_file}"
          echo "--- end ---"

          if ! grep -iq "aggregate numerators and denominators" "${output_file}"; then
            echo "::error::Prime Directive response was not found in ${output_file}" >&2
            exit 1
          fi
          if ! grep -iq "Snowflake" "${output_file}"; then
            echo "::error::Victoria capabilities response did not mention Snowflake in ${output_file}" >&2
            exit 1
          fi
