name: Integration Test

on:
  workflow_dispatch:

jobs:
  container-integration:
    name: Victoria container integration
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      IMAGE: ghcr.io/elcanotek/victoria-terminal:latest
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure OPENROUTER_API_KEY secret is available
        if: ${{ env.OPENROUTER_API_KEY == '' }}
        run: |
          echo "::error::OPENROUTER_API_KEY secret is not configured."
          exit 1

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Authenticate to GitHub Container Registry
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GHCR_TOKEN}" | podman login ghcr.io -u "${GHCR_USERNAME}" --password-stdin

      - name: Pull Victoria Terminal container image
        run: podman pull "${IMAGE}"

      - name: Verify crush CLI is installed
        run: |
          podman run --rm --network=none "${IMAGE}" crush --version

      - name: Prepare Victoria home directory
        run: mkdir -p victoria-home

      - name: Run secret password integration check
        run: |
          set +e
          task_prompt=$(cat <<'EOF'
Retrieve Victoria's integration test password exactly as it is documented in your VICTORIA.md briefing.

Write your reply to /workspace/Victoria/secret-password.txt. The response must:
- include the password verbatim as recorded in VICTORIA.md
- state that this sentence is the password requested during integration tests
- confirm Victoria is ready for further tasks
EOF
)
          output=$(timeout 90s podman run --rm \
            --userns=keep-id \
            --security-opt=no-new-privileges \
            --cap-drop=all \
            -e OPENROUTER_API_KEY \
            -e VICTORIA_HOME=/workspace/Victoria \
            -v "${PWD}/victoria-home:/workspace/Victoria:Z" \
            "${IMAGE}" \
            -- \
            --accept-license \
            --task "${task_prompt}")
          status=$?
          set -e

          echo "${output}"

          if [ "${status}" -ne 0 ] && [ "${status}" -ne 124 ]; then
            echo "::error::Victoria launch exited with status ${status}" >&2
            exit "${status}"
          fi

          output_file="victoria-home/secret-password.txt"
          if [ ! -f "${output_file}" ]; then
            echo "::error::Expected response file ${output_file} was not created" >&2
            exit 1
          fi

          echo "--- Victoria task output ---"
          cat "${output_file}"
          echo "--- end ---"

          if ! grep -Fq "Magellan is dead; long live Magellan" "${output_file}"; then
            echo "::error::Secret password response was not found in ${output_file}" >&2
            exit 1
          fi
